adminapp/urls.py
from django.urls import path
from adminapp import views
import adminapp

app_name = 'adminapp'

urlpatterns = [
   path('login/',  views.loginfun, name='login'),
   path('register/',  views.registerfun, name='register'),
   path('',  views.dashboardfun, name='dashboard'),
   path('dashboard/', views.dashboardfun, name='dashboard'),
   path('people/', views.peoplefun, name='people'),
   path('company/', views.companyfun, name='companies'),
   path('lead/', views.leadfun, name='leads'),
   path('add_lead/', views.add_leadfun, name='add_lead'),
   path('lead_assign/', views.lead_assignfun, name='lead_assign'),
   path('logout/', views.logoutfun, name='logout'),

   # path('customer/', views.customerfun, name='customers'),
   # path('import_success/', views.import_successfun, name='import_success'),
   # path('offer/', views.offerfun, name='offers'),
   # path('invoice/', views.invoicefun, name='invoice'),
   # path('quote/', views.quotefun, name='quote'),
   # path('payment/', views.paymentfun, name='payment'),
   # path('expenses/', views.expensesfun, name='expense'),
   # path('product/', views.productfun, name='product'),
   # path('product_category/', views.category_productfun, name='category_product'),



]

dth_crm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls')),
    path('telecallerapp/', include('telecallerapp.urls')),
]

telecallerapp/urls.py
from django.urls import path
from telecallerapp import views
 
app_name = 'telecallerapp' 

urlpatterns = [
   path('login/',  views.loginfun, name='login'),
   path('register/',  views.registerfun, name='register'),
   path('', views.dashboardfun, name='dashboard'),
   path('dashboard/', views.dashboardfun, name='dashboard'),
   path('customer/', views.customerfun, name='customers'),
   path('lead/', views.leadfun, name='leads'),
   path('update_lead/', views.update_leadfun, name='update_leadfun'),
   path('logout/', views.logoutfun, name='logout'),
]

telecallerapp/models.py
from django.db import models


# Create your models here.

# class Lead(models.Model):
#     type = models.ForeignKey(CompanyType, on_delete=models.CASCADE)
#     name = models.CharField(max_length=100)
#     status = models.CharField(max_length=100)
#     country = models.CharField(max_length=100)
#     email = models.EmailField()
#     phone = models.CharField(max_length=15)

#     def __str__(self):
#         return self.name

telecallerapp/forms.py
from django import forms

class LeadUploadForm(forms.Form):
    excel_file = forms.FileField()

telecallerapp/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from adminapp.models import Lead, Status, Telecaller

# Create your views here.
def registerfun(request):
    if request.method == 'POST':
        print('reg-tested')
        name = request.POST.get('name')
        country = request.POST.get('country')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(name,country,email,phone,password)
        
        try:
            print('tested')

            Telecaller.objects.create(
                name = name,
                country = country,
                phone = phone,
                email = email,
                password = password,
            )
            return redirect('telecaller:login')
        except Exception as e:
            return render(request, 'telecallerapp/pages-register.html',{'message': f'Error: {e}'})
    return render(request, 'telecallerapp/pages-register.html')

def loginfun(request):
    # if request.user.is_authenticated:
    #     return redirect('telecallerapp:dashboard')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # user = authenticate(username=username, password=password)
        try :
            telecaller = Telecaller.objects.get(
                 email = username,
                 password = password
            )
            request.session['telecaller_sessionID'] = telecaller.id
            print(request.session['telecaller_sessionID'])
            return redirect('telecallerapp:dashboard')
        except :
            print('invalid username or password !')

        # if user is not None:
        #     login(request, user)
        #     return redirect('telecallerapp:dashboard')
        # else:
        #     print('Invalid credentials') 
    return render(request, 'telecallerapp/pages-login.html')

def dashboardfun(request):
    if 'telecaller_sessionID' in request.session:
        telecaller = request.session['telecaller_sessionID']
        profile = Telecaller.objects.get(id = telecaller)
    else:
        return redirect('telecallerapp:login')
    return render(request, 'telecallerapp/pages-dashboard.html', {'profile' : profile.name})

def customerfun(request):
    return render(request, 'telecallerapp/pages-customer.html')

def leadfun(request):
    telecaller = request.session['telecaller_sessionID']
    profile = Telecaller.objects.get(id = telecaller)
    leads = Lead.objects.filter(
        telecaller = telecaller
    )
    return render(request, 'telecallerapp/pages-lead.html', {'leads' : leads, 'profile' : profile.name})

def update_leadfun(request):
    try:
        if request.method == 'POST':
            lead_id = request.POST.get('id')
            lead_status = request.POST.get('lead_status')
            print(lead_id,lead_status)
            editLeed  = Lead.objects.get(
                id=lead_id
            )
            editLeed.lead_status = lead_status

            editLeed.save()
            return JsonResponse({'message': 'Lead Status Updated successfully'})
            
    except Exception as e:
        return JsonResponse({'message': f'Error: {str(e)}'})

def logoutfun(request):
    if 'telecaller_sessionID' in request.session:
        request.session.flush()
    return redirect('telecallerapp:login')

templates/telecallerapp/components-layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <title>Dashboard - DTH CRM</title>

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'adminapp/img/favicon/favicon.ico' %}" rel="icon">
  
  <link href="{% static 'adminapp/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts --> 
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'adminapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
  <link href="{% static 'adminapp/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <div class="d-flex align-items-center justify-content-between dth-icon">
                <a href="{% url 'adminapp:dashboard' %}" class="logo d-flex align-items-center">
                  <img src="{% static 'adminapp/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">DTH CRM</span>
                </a>
              </div><!-- End Logo -->
        </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'telecallerapp:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'telecallerapp:leads' %}">
          <i class="bi bi-headphones"></i>
          <span>Leads</span>
        </a>
      </li><!-- End Customer Nav -->

      {% comment %} <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:people' %}">
          <i class="bi bi-person"></i>
          <span>People</span>
        </a>
      </li><!-- End Poeple Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:companies' %}">
          <i class="bi bi-building"></i>
          <span>Company</span>
        </a>
      </li><!-- End Company Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:leads' %}">
          <i class="bi bi-funnel"></i>
          <span>Lead</span>
        </a>
      </li><!-- End Lead Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:offers' %}">
          <i class="bi bi-file-earmark"></i>
          <span>Offer</span>
        </a>
      </li><!-- End Offer Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:invoice' %}">
          <i class="bi bi-file-text"></i>
          <span>Invoice</span>
        </a>
      </li><!-- End Invoice Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:quote' %}">
          <i class="bi bi-calendar3-range"></i>
          <span>Quote</span>
        </a>
      </li><!-- End Quote Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:expense' %}">
          <i class="bi bi-wallet"></i>
          <span>Expense</span>
        </a>
      </li><!-- End Expense Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:product' %}">
          <i class="bi bi-bag"></i>
          <span>Product</span>
        </a>
      </li><!-- End Product Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:category_product' %}">
          <i class="bi bi-chevron-double-up"></i>
          <span>Prodict Category List</span>
        </a>
      </li><!-- End Prodict Category List Page Nav --> {% endcomment %}

      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-gear"></i>
          <span>Settings</span>
        </a>
      </li> -->
      <!-- End Settings Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  {% block content %}

  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'adminapp/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'adminapp/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'adminapp/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'adminapp/js/main.js' %}"></script>

  <script>
      var options = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
      series: [70],
      labels: ['Progress'],
    }

    var chart = new ApexCharts(document.querySelector("#chart"), options);

    chart.render();
  </script>

</body>

</html>

templates/telecallerapp/pages-login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Admin Login </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'adminapp/img/favicon.png' %}" rel="icon">
  <link href="{% static 'adminapp/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'adminapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/bootstrap-icons/bootstrap-icons.css' %}"  rel="stylesheet">
  <link href="{% static 'adminapp/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.snow.css' %}" rel="stylesheet" >
  <link href="{% static 'adminapp/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}"  rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="{% static 'adminapp/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">DTH-CRM</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                  </div>

                  <form method="POST" class="row g-3 needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="email" name="username" class="form-control" id="inputUsername" required>
                        <div class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="inputPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href="{% url 'telecallerapp:register'%}">Create an account</a></p>
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'adminapp/vendor/apexcharts/apexcharts.min.js'%}"></script>
  <script src="{% static 'adminapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'adminapp/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'adminapp/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'adminapp/js/main.js' %}"></script>

</body>

</html>

templates/telecallerapp/upload_leads.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <title>Dashboard - DTH CRM</title>

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'adminapp/img/favicon/favicon.ico' %}" rel="icon">
  
  <link href="{% static 'adminapp/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts --> 
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'adminapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
  <link href="{% static 'adminapp/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <div class="d-flex align-items-center justify-content-between dth-icon">
                <a href="{% url 'adminapp:dashboard' %}" class="logo d-flex align-items-center">
                  <img src="{% static 'adminapp/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">DTH CRM</span>
                </a>
              </div><!-- End Logo -->
        </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'telecallerapp:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'telecallerapp:customers' %}">
          <i class="bi bi-headphones"></i>
          <span>Customer</span>
        </a>
      </li><!-- End Customer Nav -->

      {% comment %} <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:people' %}">
          <i class="bi bi-person"></i>
          <span>People</span>
        </a>
      </li><!-- End Poeple Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:companies' %}">
          <i class="bi bi-building"></i>
          <span>Company</span>
        </a>
      </li><!-- End Company Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:leads' %}">
          <i class="bi bi-funnel"></i>
          <span>Lead</span>
        </a>
      </li><!-- End Lead Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:offers' %}">
          <i class="bi bi-file-earmark"></i>
          <span>Offer</span>
        </a>
      </li><!-- End Offer Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:invoice' %}">
          <i class="bi bi-file-text"></i>
          <span>Invoice</span>
        </a>
      </li><!-- End Invoice Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:quote' %}">
          <i class="bi bi-calendar3-range"></i>
          <span>Quote</span>
        </a>
      </li><!-- End Quote Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:expense' %}">
          <i class="bi bi-wallet"></i>
          <span>Expense</span>
        </a>
      </li><!-- End Expense Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:product' %}">
          <i class="bi bi-bag"></i>
          <span>Product</span>
        </a>
      </li><!-- End Product Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:category_product' %}">
          <i class="bi bi-chevron-double-up"></i>
          <span>Prodict Category List</span>
        </a>
      </li><!-- End Prodict Category List Page Nav --> {% endcomment %}

      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-gear"></i>
          <span>Settings</span>
        </a>
      </li> -->
      <!-- End Settings Page Nav -->

  </ul>

  </aside><!-- End Sidebar-->

  {% block content %}
  <main id="main" class="main">
    <div class="pagetitle">
      <nav class="header-nav ms-auto display-flax">
        
        <!-- Profile -->
        <ul class="d-flex align-items-center ">
    
            <li class="nav-item dropdown pe-3">
    
              <a class="profile-circle nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                <img src="{% static 'adminapp/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
              </a><!-- End Profile Iamge Icon -->
    
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <li class="dropdown-header">
                  <h6>Username</h6>
                  <span>Admin</span>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                    <i class="bi bi-person"></i>
                    <span>My Profile</span>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Sign Out</span>
                  </a>
                </li>
    
              </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->
    
          </ul>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
    
      <!-- Third Row -->
      <div class="row">
        <div class="col-lg-12"> 

              <!-- Client List Card -->
              <div class="col-xxl-4 col-xl-12">
  
                <div class="card info-card customers-card">
  
                  <h2>Upload Leads</h2>
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Upload</button>
                  </form>
                </div>
              </div><!-- End Recent Invoices Card -->
          </div>
        </div>
      </div><!-- End Third Row -->
    </section>

  </main><!-- End #main -->
  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'adminapp/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'adminapp/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'adminapp/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'adminapp/js/main.js' %}"></script>

  <script>
      var options = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
      series: [70],
      labels: ['Progress'],
    }

    var chart = new ApexCharts(document.querySelector("#chart"), options);

    chart.render();
  </script>

</body>

</html>