adminapp/urls.py
from django.urls import path
from adminapp import views
import adminapp

app_name = 'adminapp'

urlpatterns = [
   path('login/',  views.loginfun, name='login'),
   path('register/',  views.registerfun, name='register'),
   path('',  views.dashboardfun, name='dashboard'),
   path('dashboard/', views.dashboardfun, name='dashboard'),
   path('people/', views.peoplefun, name='people'),
   path('company/', views.companyfun, name='companies'),
   path('lead/', views.leadfun, name='leads'),
   path('add_lead/', views.add_leadfun, name='add_lead'),
   path('lead_assign/', views.lead_assignfun, name='lead_assign'),
   path('logout/', views.logoutfun, name='logout'),

   # path('customer/', views.customerfun, name='customers'),
   # path('import_success/', views.import_successfun, name='import_success'),
   # path('offer/', views.offerfun, name='offers'),
   # path('invoice/', views.invoicefun, name='invoice'),
   # path('quote/', views.quotefun, name='quote'),
   # path('payment/', views.paymentfun, name='payment'),
   # path('expenses/', views.expensesfun, name='expense'),
   # path('product/', views.productfun, name='product'),
   # path('product_category/', views.category_productfun, name='category_product'),



]

dth_crm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls')),
    path('telecallerapp/', include('telecallerapp.urls')),
]

telecallerapp/urls.py
from django.urls import path
from telecallerapp import views
 
app_name = 'telecallerapp' 

urlpatterns = [
   path('login/',  views.loginfun, name='login'),
   path('register/',  views.registerfun, name='register'),
   path('', views.dashboardfun, name='dashboard'),
   path('dashboard/', views.dashboardfun, name='dashboard'),
   path('customer/', views.customerfun, name='customers'),
   path('lead/', views.leadfun, name='leads'),
   path('update_lead/', views.update_leadfun, name='update_leadfun'),
   path('logout/', views.logoutfun, name='logout'),
]

adminapp/models.py
from django.db import models

# Create your models here.

# class Group(models.Model):
#     name = models.CharField(max_length=100)

# class Client(models.Model):
#     name = models.CharField(max_length=100)
#     company = models.CharField(max_length=100)
#     country = models.CharField(max_length=50)
#     phone = models.CharField(max_length=15)
#     email = models.EmailField()
#     client_type = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name
    
# class CompanyType(models.Model):
#     name = models.CharField(max_length=50)

class Administrator(models.Model):
    name = models.CharField(max_length=100)
    username =models.EmailField()
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Telecaller(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    password = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name

class Lead(models.Model):
    telecaller = models.ForeignKey(Telecaller, null=True, blank=True, on_delete=models.SET_NULL)
    type = models.CharField(max_length=50)
    lead_status = models.CharField(max_length=50, default='pending')
    source = models.CharField(max_length=50)
    country = models.CharField(max_length=100) 
    name = models.CharField(max_length=100)  # From company or people based on the choice of type
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    status = models.CharField(max_length=100, default='pending')

    def __str__(self):
        return f"{self.type} - {self.name}"

class Status(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50, default='default_color_value')

# class Offers(models.Model):
#     lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
#     number = models.CharField(max_length=100, unique=True)
#     year = models.PositiveIntegerField()
#     status = models.CharField(max_length=50)
#     note = models.TextField()
#     current_date = models.DateField()
#     expire_date = models.DateField()

#     def __str__(self):
#         return f"Offer {self.number}"


    

adminapp/forms.py
from django import forms
from .models import Telecaller

class LeadAssignForm(forms.Form):
    telecaller = forms.ModelChoiceField(queryset=Telecaller.objects.all(), empty_label="Select", required=True)
    start = forms.IntegerField(min_value=1, required=True)
    end = forms.IntegerField(min_value=1, required=True)
    

adminapp/views.py
from email import message
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.shortcuts import redirect, render
from openpyxl import load_workbook
from .forms import LeadAssignForm
from .models import Administrator, Lead, Telecaller
from django.core.mail import send_mail
from dth_crm import settings


# Create your views here.

def loginfun(request):
    # if request.user.is_authenticated:
    #     return redirect('adminapp:dashboard')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # user = authenticate(username=username, password=password)
        try :
            admin = Administrator.objects.get(
                 username = username,
                 password = password
            )
            print(admin.id)
            request.session["admin_sessionID"] = admin.id
            return redirect('adminapp:dashboard')
        except :
            print('invalid username or password !')

        # if user is not None:
        #     login(request, user)
        #     return redirect('adminapp:dashboard')
        # else:
        #     print('Invalid credentials') 
    return render(request, 'adminapp/pages-login.html')

def registerfun(request):
    return render(request, 'adminapp/pages-register.html')

def layoutfun(request):
    administrator = request.session["admin_sessionID"]
    profile = Administrator.objects.get(id=administrator)
    return render(request, 'adminapp/components-layout.html',{'profile' : profile.name})

def dashboardfun(request):
    if 'admin_sessionID' in request.session:
        return render(request, 'adminapp/pages-dashboard.html')
    else:
        return redirect('adminapp:login')

def leadfun(request):
    if 'admin_sessionID' in request.session:
        leads_list = Lead.objects.all()

        if request.method == 'POST':
            excel_file = request.FILES['excel_file']
            wb = load_workbook(excel_file)
            ws = wb.active

            existing_phones = set(Lead.objects.values_list('phone', flat=True))

            for row in ws.iter_rows(min_row=2, values_only=True):
                type, lead_status, source, country, name, phone, email, status = row
                
                # Check if the phone numbers already exists
                if phone in existing_phones:
                    error_message = 'Phone number already exists in the Lead table.'
                    return render(request, 'adminapp/pages-lead.html', {'error_message': error_message, 'leads': leads_list })
                
                # If not, create a new Lead
                Lead.objects.create(
                    type=type, 
                    lead_status=lead_status, 
                    source=source, 
                    country=country, 
                    name=name, 
                    phone=phone, 
                    email=email, 
                    status=status
                )
            return render(request, 'adminapp/pages-lead.html', {'success_message': 'Leads imported successfully.', 'leads': leads_list })
        
        return render(request, 'adminapp/pages-lead.html', {'leads': leads_list})
    else:
        return redirect('adminapp:login')
    
def add_leadfun(request):
    try:
        if request.method == 'POST' and request.POST.get('id') == '':
            id = request.POST.get('id')
            type = request.POST.get('type')
            name = request.POST.get('name')
            lead_status = request.POST.get('lead_status')
            source = request.POST.get('source')
            country = request.POST.get('country')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            print(id,type,name,lead_status, source, country, phone,email)

            Lead.objects.create(
                type=type,
                lead_status=lead_status,
                source=source,
                country=country,
                name=name,
                phone=phone,
                email=email
            )
            return JsonResponse({'message': 'Lead added successfully'})
        
        else:
            # print('update checked')
            lead_id = request.POST.get('id')
            editLeed  = Lead.objects.get(
                id=lead_id
            )

            editLeed.type = request.POST.get('type')
            editLeed.lead_status = request.POST.get('lead_status')
            editLeed.source = request.POST.get('source')
            editLeed.country = request.POST.get('country')
            editLeed.name = request.POST.get('name')
            editLeed.phone = request.POST.get('phone')
            editLeed.email = request.POST.get('email')
            editLeed.save()
            return JsonResponse({'message': 'Lead Updated successfully'})

    except Exception as e:
        return JsonResponse({'message': f'Error: {str(e)}'})

def lead_assignfun(request):
    assigned_leads = []
    print(assigned_leads)
    telecallers = Telecaller.objects.all()

    if request.method == 'POST':
        teleemail = Telecaller.objects.get(id=1)
        form = LeadAssignForm(request.POST)

        if form.is_valid():
            telecaller = form.cleaned_data['telecaller']
            start = form.cleaned_data['start']
            end = form.cleaned_data['end']

            assigned_leads = Lead.objects.filter(
                status='pending'
            )[start:end]

            for lead in assigned_leads:
                lead.status = 'assigned'
                lead.telecaller = telecaller
                lead.save()
                 
            # Send email   
            send_mail(
                'Message form DTH CRM',
                'Now you have assigned a set of Laads. Please check your console.',
                settings.EMAIL_HOST_USER,
                [teleemail.email],  # Check that teleemail.email is valid
                fail_silently=False
            )
        return render(request, 'adminapp/lead_assign.html', {'success_message':"Successfully assigned the data"})

    else:
        form = LeadAssignForm()

    return render(request, 'adminapp/lead_assign.html', {'form': form, 'assigned_leads': assigned_leads, 'telecallers': telecallers})

def companyfun(request):
    return render(request, 'adminapp/pages-company.html')


def peoplefun(request):
    return render(request, 'adminapp/pages-people.html')

def logoutfun(request):
    if 'admin_sessionID' in request.session:
        request.session.flush()
    return redirect('adminapp:login')

# def customerfun(request):
#     return render(request, 'adminapp/pages-customer.html')

# def offerfun(request):
#     return render(request, 'adminapp/pages-offer.html')

# def invoicefun(request):
#     return render(request, 'adminapp/pages-invoice.html')

# def quotefun(request):
#     return render(request, 'adminapp/pages-quote.html')

# def paymentfun(request):
#     return render(request, 'adminapp/pages-payment.html')

# def expensesfun(request):
#     return render(request, 'adminapp/pages-expense.html')

# def productfun(request):
#     return render(request, 'adminapp/pages-product.html')

# def category_productfun(request):
#     return render(request, 'adminapp/pages-product_category.html')

templates/adminapp/components-layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <title>Dashboard - DTH CRM</title>

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'adminapp/img/favicon/favicon.ico' %}" rel="icon">
  
  <link href="{% static 'adminapp/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts --> 
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'adminapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
  <link href="{% static 'adminapp/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <div class="d-flex align-items-center justify-content-between dth-icon">
                <a href="{% url 'adminapp:dashboard' %}" class="logo d-flex align-items-center">
                  <img src="{% static 'adminapp/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">DTH CRM</span>
                </a>
              </div><!-- End Logo -->
        </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'adminapp:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:people' %}">
          <i class="bi bi-person"></i>
          <span>People</span>
        </a>
      </li><!-- End Poeple Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:companies' %}">
          <i class="bi bi-building"></i>
          <span>Company</span>
        </a>
      </li><!-- End Company Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:leads' %}">
          <i class="bi bi-funnel"></i>
          <span>Lead</span>
        </a>
      </li><!-- End Lead Nav -->

      {% comment %} <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:customers' %}">
          <i class="bi bi-headphones"></i>
          <span>Customer</span>
        </a>
      </li><!-- End Customer Nav --> 

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:offers' %}">
          <i class="bi bi-file-earmark"></i>
          <span>Offer</span>
        </a>
      </li><!-- End Offer Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:invoice' %}">
          <i class="bi bi-file-text"></i>
          <span>Invoice</span>
        </a>
      </li><!-- End Invoice Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:quote' %}">
          <i class="bi bi-calendar3-range"></i>
          <span>Quote</span>
        </a>
      </li><!-- End Quote Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:expense' %}">
          <i class="bi bi-wallet"></i>
          <span>Expense</span>
        </a>
      </li><!-- End Expense Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:product' %}">
          <i class="bi bi-bag"></i>
          <span>Product</span>
        </a>
      </li><!-- End Product Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:category_product' %}">
          <i class="bi bi-chevron-double-up"></i>
          <span>Prodict Category List</span>
        </a>
      </li><!-- End Prodict Category List Page Nav --> {% endcomment %}

      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-gear"></i>
          <span>Settings</span>
        </a>
      </li> -->
      <!-- End Settings Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->
  
  <main id="main" class="main">

  <div class="pagetitle">
    <nav class="header-nav ms-auto dis-flax">
      <ol class="breadcrumb">
        
      </ol>
      
      <!-- Profile -->
      <ul class="d-flex align-items-center ">
  
          <li class="nav-item dropdown pe-3">
  
            <a class="profile-circle nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <img src="{% static 'adminapp/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            </a><!-- End Profile Iamge Icon -->
  
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li class="dropdown-header">
                <span>Admin</span>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                  <i class="bi bi-person"></i>
                  <span>My Profile</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'adminapp:logout' %}">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
  
            </ul><!-- End Profile Dropdown Items -->
          </li><!-- End Profile Nav -->
  
        </ul>
    </nav>
  </div><!-- End Page Title -->

    
  {% block content %}

  {% endblock %}
  </main>
  

 

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright 
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'adminapp/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'adminapp/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'adminapp/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'adminapp/js/main.js' %}"></script>

  <script>
      var options = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
      series: [70],
      labels: ['Progress'],
    }

    var chart = new ApexCharts(document.querySelector("#chart"), options);

    chart.render();
  </script>

</body>

</html>

templates/adminapp/import_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Done</h1>
</body>
</html>

templates/adminapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - DTH CRM</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'adminapp/img/favicon/favicon.ico' %}" rel="icon">
  
  <link href="{% static 'adminapp/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts --> 
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'adminapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
  <link href="{% static 'adminapp/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'adminapp/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'adminapp:dashboard' %}" class="logo d-flex align-items-center">
        <img src="{% static 'adminapp/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">DTH CRM</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'adminapp/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">Username</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Username</h6>
              <span>Admin</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'adminapp:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:customers' %}">
          <i class="bi bi-headphones"></i>
          <span>Customer</span>
        </a>
      </li><!-- End Customer Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:people' %}">
          <i class="bi bi-person"></i>
          <span>People</span>
        </a>
      </li><!-- End Poeple Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:companies' %}">
          <i class="bi bi-building"></i>
          <span>Company</span>
        </a>
      </li><!-- End Company Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:leads' %}">
          <i class="bi bi-funnel"></i>
          <span>Lead</span>
        </a>
      </li><!-- End Lead Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:offers' %}">
          <i class="bi bi-file-earmark"></i>
          <span>Offer</span>
        </a>
      </li><!-- End Offer Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:invoice' %}">
          <i class="bi bi-file-text"></i>
          <span>Invoice</span>
        </a>
      </li><!-- End Invoice Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:quote' %}">
          <i class="bi bi-calendar3-range"></i>
          <span>Quote</span>
        </a>
      </li><!-- End Quote Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:expense' %}">
          <i class="bi bi-wallet"></i>
          <span>Expense</span>
        </a>
      </li><!-- End Expense Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:product' %}">
          <i class="bi bi-bag"></i>
          <span>Product</span>
        </a>
      </li><!-- End Product Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminapp:category_product' %}">
          <i class="bi bi-chevron-double-up"></i>
          <span>Prodict Category List</span>
        </a>
      </li><!-- End Prodict Category List Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-gear"></i>
          <span>Settings</span>
        </a>
      </li><!-- End Settings Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'adminapp/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'adminapp/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'adminapp/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'adminapp/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'adminapp/js/main.js' %}"></script>

  <script>
      var options = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
      series: [70],
      labels: ['Progress'],
    }

    var chart = new ApexCharts(document.querySelector("#chart"), options);

    chart.render();
  </script>

</body>

</html>